# Generated by Django 3.1.7 on 2021-03-18 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Organizasyon Adı')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Organizasyondaki Pozisyonu')),
                ('related_institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='İlgili Kuruluş Adı')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Sosyal Aktiviteler',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sertifika ya da Lisans Adı')),
                ('related_institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='İlgili Kuruluş Adı')),
                ('certificate_stat', models.BooleanField(default=False, verbose_name='Bu sertifikanın geçerliliği sona ermez')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Alınma Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Sona Erme Tarihi')),
                ('certificate_url', models.URLField(blank=True, null=True, verbose_name='Sertifika Linki')),
                ('certificate_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sertifika Kimliği')),
                ('Description', models.TextField(null=True, verbose_name='Kısa Açıklama')),
            ],
            options={
                'verbose_name': 'Sertifika Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='Contactinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon numarası')),
            ],
            options={
                'verbose_name': 'İletişim Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='Giriş Tarihi')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='Mezuniyet Tarihi')),
                ('school_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Okul Adı')),
                ('faculty_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fakülte')),
                ('school_department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bölüm')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Kısa Açıklama')),
            ],
            options={
                'verbose_name': 'Eğitim Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Şirket Adı')),
                ('position', models.CharField(max_length=100, verbose_name='Pozisyon')),
                ('employment_type', models.CharField(max_length=100, verbose_name='İstihdam Türü')),
                ('job_admission_date', models.DateField(blank=True, null=True, verbose_name='İşe Giriş Tarihi')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='İşten Ayrılma Tarihi')),
                ('short_description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Kısa Açıklama')),
            ],
            options={
                'verbose_name': 'Tecrübe',
            },
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_list', models.TextField(blank=True, max_length=500, null=True, verbose_name='İlgi Alanları')),
            ],
            options={
                'verbose_name': 'İlgi Alanları',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='Proje Adı')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Proje Başlangıç Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Proje Bitiş Tarihi')),
                ('project_url', models.URLField(blank=True, null=True, verbose_name='Proje Linki')),
                ('related_institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='İlgili Kuruluş Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Proje Bilgileri')),
            ],
            options={
                'verbose_name': 'Projeler',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Yetkinlik Adı')),
                ('knowledge', models.CharField(blank=True, max_length=50, null=True, verbose_name='Yetkinlik Düzeyi')),
            ],
            options={
                'verbose_name': 'Yetkinlikler',
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='İsim')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Soyisim')),
                ('user_name', models.CharField(max_length=30, unique=True, verbose_name='Kullanıcı Adı')),
                ('profession', models.CharField(blank=True, max_length=30, null=True, verbose_name='Meslek')),
                ('maritalstat', models.BooleanField(default=False, verbose_name='Evli')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Profil Fotoğrafı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='Computer_Skills',
            fields=[
                ('skills_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cvapp.skills')),
                ('com_program', models.CharField(blank=True, max_length=50, null=True, verbose_name='Program Adı')),
            ],
            bases=('cvapp.skills',),
        ),
        migrations.CreateModel(
            name='Language_Skills',
            fields=[
                ('skills_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cvapp.skills')),
                ('language', models.CharField(blank=True, max_length=50, null=True, verbose_name='Yabancı Dil')),
                ('reading_level', models.CharField(blank=True, max_length=30, null=True, verbose_name='Okuma Yetkinliği')),
                ('writing_level', models.CharField(blank=True, max_length=30, null=True, verbose_name='Yazma Yetkinliği')),
                ('speaking_level', models.CharField(blank=True, max_length=30, null=True, verbose_name='Konuşma Yetkinliği')),
            ],
            bases=('cvapp.skills',),
        ),
    ]
