# Generated by Django 3.1.7 on 2021-03-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deneme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_list', models.TextField(blank=True, max_length=500, null=True, verbose_name='İlgi Alanları')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'İletişim Bilgisi', 'verbose_name_plural': 'İletişim Bilgileri'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Tecrübe', 'verbose_name_plural': 'Tecrübeler'},
        ),
    ]
